name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'yusys-cloud'
        reponame: 'ai-tools-ui'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
